# Generated by Django 4.2.23 on 2025-08-28 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulestudent',
            name='status',
        ),
        migrations.AlterField(
            model_name='modulestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
