# Generated by Django 4.2.23 on 2025-08-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0004_modulechatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='active_chat',
            field=models.BooleanField(default=False),
        ),
    ]
