
services:
  backend:
    build: ./Backend
    env_file:
      - ./Backend/.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: learningapp
      POSTGRES_PASSWORD: learningapp
      POSTGRES_DB: learningapp
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    build: ./frontEnd
    ports:
      - "80:80"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: learningapp
      POSTGRES_PASSWORD: learningapp
      POSTGRES_DB: learningapp
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
